version: "2"
services:

  litbox-lit:
    image: lit
    restart: always
    expose:
      - "8001"
    volumes:
      - ./data/lit:/root/.lit

  litbox-tunnel:
    image: litbox-tunnel
    restart: always
    ports:
      - "42924:22"
    volumes:
      - ./data/keys:/root/keys

  litbox-admin:
    image: litbox-admin
    restart: always
    expose:
      - "3000"
    ports:
      - "80:3000"
    volumes:
      - ./data/secrets:/root/secrets 

networks:    
  default:
    external:
      name: litbox-network
